spring:
  application:
    name: showmethecs
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, account_email, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://localhost:5432/showmethecs
    username: showmethecs
    password: showmethecs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#devtools 설정
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
# Gemini 설정
google:
  api-key: ${GOOGLE_API_KEY}
  model: models/gemini-1.5-flash-latest