name: 📌 General Task
description: 기능 개발, 버그 수정, 리팩토링 등 모든 작업에 사용하는 템플릿
title: "[Task]: "
labels: []
body:
  - type: input
    id: summary
    attributes:
      label: 요약
      description: 어떤 작업인지 한 줄 요약해주세요
      placeholder: ex) 로그인 기능 추가, 빌드 오류 수정
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 작업의 배경, 목적, 요구사항 등을 적어주세요
      placeholder: |
        - 문제 상황
        - 기대 동작
        - 참고 자료

  - type: textarea
    id: todo
    attributes:
      label: 할 일 (TODO)
      description: 체크리스트 형식으로 작성하세요
      value: |
        - [ ] 할 일 1
        - [ ] 할 일 2

  - type: textarea
    id: etc
    attributes:
      label: 비고
      description: 추가 메모가 있다면 적어주세요
